### ISSUE TITLE
Recommend turning on NUCs automatically after a power failure

### ISSUE THREAD

**Issue by eaon** [freedomofpress/securedrop-docs#370] opened 2022-08-09 18:51 UTC
## Describe the change

For NUCs that support it (possible that all of them do?), I think it'd be a good idea to recommend auto-power-on on power-failure. Since the machines are not encrypted anyway, I believe there wouldn't be any security implications either (ping @l3th3!)

I'm not at a NUC at the moment but from quickly browsing the internet I understand this should be possible via **Power ▸ Secondary Power Settings ▸ After Power Failure** use the drop-down menu to select **Power On**.

## How will this impact users?

Admins wouldn't have to come in to manually power on devices in the event of a power failure.

**Comment by nathandyer** [comment] 2022-09-15 19:22
Definitely a great idea, but I believe this is a duplicate of Issue #186. Will close this one out, then open a PR against #186.

**Closed by nathandyer** 2022-09-15 19:22 UTC
